// ================================================================
// TestCase Studio — Playwright Script
// Name  : Recorded_Test
// Date  : 15/05/2026, 22:23:08
// Steps : 5
// ================================================================
// RUN:
//   npm install && npx playwright install chromium
//   node Recorded_Test.spec.js
// ================================================================
// LOCATOR STRATEGY per element step (tried in order):
//   1. Primary XPath (recorded)
//   2. Primary CSS   (recorded)
//   3. Index-based XPath   e.g. (//button)[4]
//   4. Text-based XPath    e.g. //button[normalize-space()="OK"]
//   5. Partial-ID XPath    e.g. //input[contains(@id,"field-")]
// ================================================================

'use strict';
const { chromium } = require('playwright');

// ─── findElement: tries every locator in order, first match wins ────────────
// Generated by TestCase Studio. Handles dynamic IDs automatically.
async function findElement(locators, stepDesc) {
  const errs = [];
  for (const { label, loc } of locators) {
    try {
      await loc.waitFor({ state: 'attached', timeout: 3000 });
      if (await loc.count() > 0) {
        process.stdout.write('  [✓] ' + stepDesc + ' → ' + label + '\n');
        return loc.first();
      }
      errs.push(label + ': 0 elements matched');
    } catch (e) {
      errs.push(label + ': ' + e.message.split('\n')[0]);
    }
  }
  throw new Error(
    'Element not found for: "' + stepDesc + '"\n' +
    errs.map((e, i) => '  ' + (i + 1) + '. ' + e).join('\n') + '\n' +
    'Tip: Re-record this step if the page structure changed.'
  );
}
// ─────────────────────────────────────────────────────────────────────────────

(async () => {
  const browser = await chromium.launch({ headless: false, slowMo: 80 });
  const context = await browser.newContext();
  const page    = await context.newPage();

  // ── 5 Recorded Steps ─────────────────────────────────────

  // Step 1: Open website
  await page.goto('http://192.168.1.168:8080');

  // Step 2: Click on "Cadastro"
  // Playwright: page.locator('a[routerlink=\'cadastrar\']')
  const el_2 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//a[normalize-space()=\'Cadastro\']') },
    { label: 'CSS (primary)', loc: page.locator('a[routerlink=\'cadastrar\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[2]') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Cadastro"');
  await el_2.click();

  // Step 3: Enter "Rolfi" into "Nome"
  // Playwright: page.locator('#nome')
  const el_3 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'nome\']') },
    { label: 'CSS (primary)', loc: page.locator('#nome') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Enter "Rolfi" into "Nome"');
  await el_3.fill(`Rolfi`);

  // Step 4: Enter "Rua Um" into "Endereço"
  // Playwright: page.locator('#endereco')
  const el_4 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'endereco\']') },
    { label: 'CSS (primary)', loc: page.locator('#endereco') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[2]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Enter "Rua Um" into "Endereço"');
  await el_4.fill(`Rua Um`);

  // Step 5: Click on "Cadastrar"
  // Playwright: page.locator('button')
  const el_5 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[contains(text(),\'Cadastrar\')]') },
    { label: 'CSS (primary)', loc: page.locator('button') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Cadastrar\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Cadastrar"');
  await el_5.click();

  console.log('\n✓ All 5 steps passed.');
  await browser.close();
})().catch(err => {
  console.error('\n✗ Test failed:', err.message);
  process.exit(1);
});