// ================================================================
// TestCase Studio — Playwright Script
// Name  : Recorded_Test
// Date  : 15/05/2026, 22:53:21
// Steps : 2
// ================================================================
// RUN:
//   npm install && npx playwright install chromium
//   node Recorded_Test.spec.js
// ================================================================
// LOCATOR STRATEGY per element step (tried in order):
//   1. Primary XPath (recorded)
//   2. Primary CSS   (recorded)
//   3. Index-based XPath   e.g. (//button)[4]
//   4. Text-based XPath    e.g. //button[normalize-space()="OK"]
//   5. Partial-ID XPath    e.g. //input[contains(@id,"field-")]
// ================================================================

'use strict';
const { chromium } = require('playwright');

// ─── findElement: tries every locator in order, first match wins ────────────
// Generated by TestCase Studio. Handles dynamic IDs automatically.
async function findElement(locators, stepDesc) {
  const errs = [];
  for (const { label, loc } of locators) {
    try {
      await loc.waitFor({ state: 'attached', timeout: 3000 });
      if (await loc.count() > 0) {
        process.stdout.write('  [✓] ' + stepDesc + ' → ' + label + '\n');
        return loc.first();
      }
      errs.push(label + ': 0 elements matched');
    } catch (e) {
      errs.push(label + ': ' + e.message.split('\n')[0]);
    }
  }
  throw new Error(
    'Element not found for: "' + stepDesc + '"\n' +
    errs.map((e, i) => '  ' + (i + 1) + '. ' + e).join('\n') + '\n' +
    'Tip: Re-record this step if the page structure changed.'
  );
}
// ─────────────────────────────────────────────────────────────────────────────

(async () => {
  const browser = await chromium.launch({ headless: false, slowMo: 80 });
  const context = await browser.newContext();
  const page    = await context.newPage();

  // ── 2 Recorded Steps ─────────────────────────────────────

  // Step 1: Open website
  await page.goto('http://192.168.1.168:8080/listar');

  // Step 2: Click on "Excluir"
  // Playwright: page.locator('body > app-root:nth-child(1) > app-listar-cliente:nth-child(3) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(5) > td:nth-child(5) > a:nth-child(1) > span:nth-child(2)')
  const el_2 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//tbody/tr[5]/td[4]/a[1]/span[2]') },
    { label: 'CSS (primary)', loc: page.locator('body > app-root:nth-child(1) > app-listar-cliente:nth-child(3) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(5) > td:nth-child(5) > a:nth-child(1) > span:nth-child(2)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//span)[49]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//span[normalize-space()=\'Excluir\']') },
    { label: 'nth-of-type CSS', loc: page.locator('span:nth-of-type(2)') }
  ], 'Click on "Excluir"');
  await el_2.click();

  console.log('\n✓ All 2 steps passed.');
  await browser.close();
})().catch(err => {
  console.error('\n✗ Test failed:', err.message);
  process.exit(1);
});